### ISSUE TITLE
Obey HTTP_PROXY and HTTPS_PROXY env variable

### ISSUE THREAD

**Issue by c33s** [hisabimbola/slack-history-export#12]
the app should check if the env variables are set and should connect through the proxy if set.

**Comment by hisabimbola** [comment]
This app does not control the connection/requests to slack, hence cannot implement this feature. You can submit a PR on the module [here](https://github.com/germanrcuriel/slack-api-client)

Closing this for now, you can reopen if you have further questions or clarification on this.
