### ISSUE TITLE
How long should this process take?

### ISSUE THREAD

**Issue by comradeDa** [hisabimbola/slack-history-export#15]
Just testing this out with a small two-message direct-message chain, and it seems to be taking an obnoxiously long time. Not sure if it's actually doing anything since the 'working...' thing isn't giving me any feedback. I am using a T2 micro on AWS, which isn't fast at all, but it's two messages.

I may have cocked up the installation somewhere along the line, I'm using the very cut down version of linux that amazon offers for web servers. npm install worked ok.

**Comment by comradeDa** [comment]
Oh, it would appear that its the csv loop bug. Alas.

**Comment by hisabimbola** [comment]
Similar to #14

**Comment by comradeDa** [comment]
Exactly that.

**Comment by hisabimbola** [comment]
Fixed.
