### ISSUE TITLE
Lots of json

### ISSUE THREAD

**Issue by comradeDa** [hisabimbola/slack-history-export#16]
The files seem to pile on the .json.json when exported. Is that right?

**Comment by hisabimbola** [comment]
Hi @comradeDa can you please be more explicit on this issue.

**Comment by comradeDa** [comment]
So, at the end of the file names produced, there is "[filename].json.json.json". Which is a lot of json. or sometimes .json.csv.json. One way or another, most of these file extensions are probably redundant.

**Comment by hisabimbola** [comment]
Thanks @comradeDa. I was able to reproduce this behaviour, will fix
