### ISSUE TITLE
Option for human readable date format?

### ISSUE THREAD

**Issue by nuna-alan** [hisabimbola/slack-history-export#18]
It would be great to have an option for date output in YYYY-MM-DD HH:MM:ss

**Comment by hisabimbola** [comment]
Hi @nuna-alan, if you use previous versions, the date was in readable format, but base on some suggestions that the export dump should be able to be reimported into slack, I updated the date format to what slack supported.

Not sure how to go about this, but you can try previous versions if you really want to maintain the human readable date format.

**Comment by nuna-alan** [comment]
Maybe add a '-h' commandline option to toggle the formatting? I'd do it
myself but my JS skills aren't great.

On Tuesday, May 31, 2016, Abimbola Idowu notifications@github.com wrote:

> Hi @nuna-alan https://github.com/nuna-alan, if you use previous
> versions, the date was in readable format, but base on some suggestions
> that the export dump should be able to be reimported into slack, I updated
> the date format to what slack supported.
> 
> Not sure how to go about this, but you can try previous versions if you
> really want to maintain the human readable date format.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hisabimbola/slack-history-export/issues/18#issuecomment-222827960,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALCk2kP2Ejz_wd4kPzFHUA-UKCVOiPkEks5qHKkcgaJpZM4Iq3AV
> .

## 

_Alan Berman_
Information Technology
415.942.5049
_Nuna_
650 Townsend Street, Suite 425
San Francisco, CA 94103

**Comment by hisabimbola** [comment]
Thanks for your input, I will consider and see how I can modify the current options to accommodate this when next am working on this. Let me know if you need any other help.

Will close this issue now, you can reopen if you have any other question/challenges.
