### ISSUE TITLE
Please Add Public/Private Channel Support

### ISSUE THREAD

**Issue by humor4fun** [hisabimbola/slack-history-export#2]
You've done a great job with this little tool, I appreciate that. It would be fantastic if it also supported specific channel archive pull requests. Being able to do a "-u self" to get all the public/private channels and DMs that the token has been involved in would be amazing too.

**Comment by hisabimbola** [comment]
Hey @humor4fun Thanks for the feature request. I will resume work on this and update shortly, meanwhile, let me know if you working on this already.

**Comment by mitquinn** [comment]
This is an awesome tool. I would really love to be able to export channels. I am integrating it with a bot now the ability to export channels would really be amazing. 

Thanks for the hard work and if you need any help let me know.

**Comment by humor4fun** [comment]
Great work. I've written a wrapper to help automate the logging process for myself.

**Comment by hisabimbola** [comment]
Cool. Good job @humor4fun
