### ISSUE TITLE
Private Channels Does Not Exist

### ISSUE THREAD

**Issue by Doxortho** [hisabimbola/slack-history-export#25]
http://image.prntscr.com/image/3642cdb0390a41f3a51ab47e34d16d3d.png

It is working for me when I am using it for public channels but for private channels I get the error message that the channel does not exist. I have checked the channel name and tried it for different channels and they are all correct. Only the private channels do not work.

**Comment by hisabimbola** [comment]
What is the command you are running? @Doxortho

**Comment by Doxortho** [comment]
I'm using "slack-history-export -t [token] -c [channel]"

It works for channels that are not private and creates the json file but when I use the name of a channel that is private, it tells me that channel does not exist.

**Comment by hisabimbola** [comment]
Private channels are called **groups** in slack, so you need to use the `-g` command.

``` bash
slack-history-export -t [token] -g [groupName]
```
