### ISSUE TITLE
new version 0.4.0 do not work

### ISSUE THREAD

**Issue by alexandrezia** [hisabimbola/slack-history-export#28]
Upgraded to 0.4.0 and cant export DM anymore:  [TypeError: Converting circular structure to JSON]
Reverted to 0.3.0 and it's working again

**Comment by hisabimbola** [comment]
Thanks for reporting, will look into this ASAP. Can you provide what command you ran on the tool.

**Comment by alexandrezia** [comment]
slack-history-export --token XXXXXXXXXXXXX --type dm --username john.doe --directory /private/var/tmp/slack-dump-iYCLFv --filename john.doe.json --format json

**Comment by hisabimbola** [comment]
Thanks a bunch @alexandrezia for reporting, a commit got lost during publishing, fixed it and deploy. You can upgrade now. Adding test for this tool #21 so mistakes like this don't happen again.

**Comment by hisabimbola** [comment]
Please reopen is this still exist...

**Comment by alexandrezia** [comment]
Thanks a lot, already tested and working OK now!
