### ISSUE TITLE
Archived

### ISSUE THREAD

**Issue by NamespaceValentine** [hisabimbola/slack-history-export#4]
Will there be any plans to implement archived DM exporting? Is that even possible?

**Comment by hisabimbola** [comment]
Yeah, you should be able to export archived DM, I just tried it and it worked.

**Comment by NamespaceValentine** [comment]
Sadly it looks like its just the free message limit that is stopping me, ty

**Comment by humor4fun** [comment]
I was pleasantly surprised to find that I could export archived messages with no problem at all. Even for employees whose account has been deactivated.

**Comment by hisabimbola** [comment]
Yeah, slack does not delete data. Nice design decision for them.

**Comment by NamespaceValentine** [comment]
Yeah it just seems that the export process does not work for archived DMs on the free tier. You can export public channel archives.

**Comment by hisabimbola** [comment]
To better put, on free tier messages are truncated/deleted. So not like it does not work, it does not exist at all because it has been deleted.

**Comment by NamespaceValentine** [comment]
They still have the information, because you can upgrade to get to it, it is just, as you said, truncated. You cannot access it through their API without unlocking them. Interestingly, they allow you to export all global channel messages without the limit through their export dump, and if you use a compliance dump that Slack approves, you can get access to everyone's full history of DMs. However, you cannot export just your own DM history, and so you cannot bypass the truncation through that method for DMs short of that compliance export.
