### ISSUE TITLE
Seems private channel export is not working though

### ISSUE THREAD

**Issue by univert** [hisabimbola/slack-history-export#6]

**Comment by hisabimbola** [comment]
Hi @univert, Thanks for your raising your concern with the tool.

Can you provide the error if any? or a better context. I tried it and it worked here.

**Comment by univert** [comment]
Sorry my bad. I did not realize that -T group must be used with -g and -T channel must be used with -c
works like a charm eventually
Seems this is a useability issue.

**Comment by hisabimbola** [comment]
Yeah, thanks for your feedback @univert I felt so too. I look forward to improving the options feature. Your input on how I can make this better is welcome.

**Comment by univert** [comment]
I guess the -T is redundant in some cases. So it should not be a required option.
I mean -c obviously implies -T channel
-g obviously implies -T group
-u implies -T user
...

**Comment by c33s** [comment]
i have the same problem here. i cannot export private channels.

```
slack-history-export --token "mytoken" --type channel --channel temp
slack-history-export -t "mytoken" -T "channel" -c "temp"
```

both commands lead to a 

```
[Error: Channel does not exist. Check channel name and try again.]
Error: Channel does not exist. Check channel name and try again.
```

should this tool work on free slack accounts?

**Comment by hisabimbola** [comment]
Hello @c33s A private channel is a group. Try changing `-c` to `-g` and let me know if it works. Also, the `-T` option is not required again. I will update the readme shortly.

**Comment by c33s** [comment]
awesome. it works when i am using -g . thanks for your cool app.

in general the flags are quite confusing. they should speak for themself (why is a channel a group?)

**Comment by hisabimbola** [comment]
I totally agree to that @c33s, hence, the decision to remove the `T` flag. However, a `channel` is different from a `group` on slack. Channels are public while groups are private. This is standard slack terminologies.

Any suggestions that will help make the tool more usable are welcome

**Comment by c33s** [comment]
maybe just add some examples to the readme
- export all public messages
- export a specific channel
- export a private channel
- ...

just add some variations which make sense, then users which come here just have to copy and paste the code, add their token and are done.

**Comment by hisabimbola** [comment]
Okay thanks @c33s, will update.
