### ISSUE TITLE
Filename is Required

### ISSUE THREAD

**Issue by humor4fun** [hisabimbola/slack-history-export#8]
When specifying the output directory using "--directory [value]" a filename parameter must also be supplied or else the execution fails and produces this message:

Error Occured: option type must me present. Type 'slack-history-export --help' to view options

Should the directory+filename always be paired? if so, this is not a bug but a documentation slip up. I assumed the filename would remain defaulted when specifying directory.

**Comment by humor4fun** [comment]
I think i've got a bad report here. Something is certainly wonky, but I haven't figured out what is causing the bug. The command I'm using is

slack-history-export --token "$slack_token" --type 'group' --group "$dm" --directory "$directory/$dm/" --filename "$dm.json"

and now i'm getting a stack trace saying missing token.

**Comment by hisabimbola** [comment]
Did you get this fix @humor4fun? Not sure I got what the issue is

**Comment by humor4fun** [comment]
Yes I did. I was getting an extra " in my api token which was randomly
throwing off everything else as I was testing.

On Sunday, April 24, 2016, Abimbola Idowu notifications@github.com wrote:

> Did you get this fix @humor4fun https://github.com/humor4fun? Not sure
> I got what the issue is
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hisabimbola/slack-history-export/issues/8#issuecomment-213910567

## 

---

Chris Holt
http://humor4fun.tumblr.com/
